language: node_js
node_js:
 - "node"
cache:
  directories:
    - "node_modules"
jobs:
  include:
    - stage: test
      script: npm test
    - stage: build
      script: npm run build
stages:
  - test
  - build
after_success: 'npm run coveralls'